/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : SERVO1_TimerUnit.h
**     Project     : ServoMotor
**     Processor   : MKL46Z256VLL4
**     Component   : TimerUnit_LDD
**     Version     : Component 01.164, Driver 01.11, CPU db: 3.00.000
**     Repository  : Kinetis
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-10-25, 11:10, # CodeGen: 5
**     Abstract    :
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
**     Settings    :
**          Component name                                 : SERVO1_TimerUnit
**          Module name                                    : TPM0
**          Counter                                        : TPM0_CNT
**          Counter direction                              : Up
**          Counter width                                  : 16 bits
**          Value type                                     : uint16_t
**          Input clock source                             : Internal
**            Counter frequency                            : Auto select
**          Counter restart                                : On-match
**            Period device                                : TPM0_MOD
**            Period                                       : 20 ms
**            Interrupt                                    : Disabled
**          Channel list                                   : 1
**            Channel 0                                    : 
**              Mode                                       : Compare
**                Compare                                  : TPM0_C4V
**                Offset                                   : 1.5 ms
**                Output on compare                        : Set
**                  Output on overrun                      : Clear
**                  Initial state                          : Low
**                  Output pin                             : LCD_P44/PTD4/LLWU_P14/SPI1_PCS0/UART2_RX/TPM0_CH4
**                  Output pin signal                      : 
**                Interrupt                                : Disabled
**          Initialization                                 : 
**            Enabled in init. code                        : yes
**            Auto initialization                          : no
**            Event mask                                   : 
**              OnCounterRestart                           : Disabled
**              OnChannel0                                 : Disabled
**              OnChannel1                                 : Disabled
**              OnChannel2                                 : Disabled
**              OnChannel3                                 : Disabled
**              OnChannel4                                 : Disabled
**              OnChannel5                                 : Disabled
**              OnChannel6                                 : Disabled
**              OnChannel7                                 : Disabled
**          CPU clock/configuration selection              : 
**            Clock configuration 0                        : This component enabled
**            Clock configuration 1                        : This component disabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init               - LDD_TDeviceData* SERVO1_TimerUnit_Init(LDD_TUserData *UserDataPtr);
**         Enable             - LDD_TError SERVO1_TimerUnit_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable            - LDD_TError SERVO1_TimerUnit_Disable(LDD_TDeviceData *DeviceDataPtr);
**         GetPeriodTicks     - LDD_TError SERVO1_TimerUnit_GetPeriodTicks(LDD_TDeviceData *DeviceDataPtr,...
**         ResetCounter       - LDD_TError SERVO1_TimerUnit_ResetCounter(LDD_TDeviceData *DeviceDataPtr);
**         GetCounterValue    - SERVO1_TimerUnit_TValueType SERVO1_TimerUnit_GetCounterValue(LDD_TDeviceData...
**         SetOffsetTicks     - LDD_TError SERVO1_TimerUnit_SetOffsetTicks(LDD_TDeviceData *DeviceDataPtr,...
**         GetOffsetTicks     - LDD_TError SERVO1_TimerUnit_GetOffsetTicks(LDD_TDeviceData *DeviceDataPtr,...
**         SelectOutputAction - LDD_TError SERVO1_TimerUnit_SelectOutputAction(LDD_TDeviceData...
**
**     Copyright : 1997 - 2015 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file SERVO1_TimerUnit.h
** @version 01.11
** @brief
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
*/         
/*!
**  @addtogroup SERVO1_TimerUnit_module SERVO1_TimerUnit module documentation
**  @{
*/         

#ifndef __SERVO1_TimerUnit_H
#define __SERVO1_TimerUnit_H

/* MODULE SERVO1_TimerUnit. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "TPM_PDD.h"
#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif 


#ifndef __BWUserType_SERVO1_TimerUnit_TValueType
#define __BWUserType_SERVO1_TimerUnit_TValueType
  typedef uint16_t SERVO1_TimerUnit_TValueType ; /* Type for data parameters of methods */
#endif
#define SERVO1_TimerUnit_CNT_INP_FREQ_U_0 0x002DC6C0UL /* Counter input frequency in Hz */
#define SERVO1_TimerUnit_CNT_INP_FREQ_U_0_CFG_0 0x002DC6C0UL /* Counter input frequency in Hz for Clock configuration 0 */
#define SERVO1_TimerUnit_CNT_INP_FREQ_R_0 3000003.000003F /* Counter input frequency in Hz */
#define SERVO1_TimerUnit_CNT_INP_FREQ_R_0_CFG_0 3000003.000003F /* Counter input frequency in Hz for Clock configuration 0 */
#define SERVO1_TimerUnit_CNT_INP_FREQ_COUNT 0U /* Count of predefined counter input frequencies */
#define SERVO1_TimerUnit_PERIOD_TICKS 0xEA60UL /* Initialization value of period in 'counter ticks' */
#define SERVO1_TimerUnit_NUMBER_OF_CHANNELS 0x01U /* Count of predefined channels */
#define SERVO1_TimerUnit_COUNTER_WIDTH 0x10U /* Counter width in bits  */
#define SERVO1_TimerUnit_COUNTER_DIR DIR_UP /* Direction of counting */
#define SERVO1_TimerUnit_OFFSET_0_TICKS 0x1194ul /* Initialization value of offset as 'counter ticks' for channel 0 */
/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define SERVO1_TimerUnit_PRPH_BASE_ADDRESS  0x40038000U
  
/* Methods configuration constants - generated for all enabled component's methods */
#define SERVO1_TimerUnit_Init_METHOD_ENABLED /*!< Init method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_Enable_METHOD_ENABLED /*!< Enable method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_Disable_METHOD_ENABLED /*!< Disable method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_GetPeriodTicks_METHOD_ENABLED /*!< GetPeriodTicks method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_ResetCounter_METHOD_ENABLED /*!< ResetCounter method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_GetCounterValue_METHOD_ENABLED /*!< GetCounterValue method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_SetOffsetTicks_METHOD_ENABLED /*!< SetOffsetTicks method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_GetOffsetTicks_METHOD_ENABLED /*!< GetOffsetTicks method of the component SERVO1_TimerUnit is enabled (generated) */
#define SERVO1_TimerUnit_SelectOutputAction_METHOD_ENABLED /*!< SelectOutputAction method of the component SERVO1_TimerUnit is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */



/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_Init (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* SERVO1_TimerUnit_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_Enable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Enables the component - it starts the signal generation.
**         Events may be generated (see SetEventMask). The method is
**         not available if the counter can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_Disable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Disables the component - it stops signal generation and
**         events calling. The method is not available if the counter
**         can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_GetPeriodTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the number of counter ticks before re-initialization.
**         See also method [SetPeriodTicks]. This method is available
**         only if the property ["Counter restart"] is switched to
**         'on-match' value.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         TicksPtr        - Pointer to return value of the
**                           number of counter ticks before
**                           re-initialization
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_GetPeriodTicks(LDD_TDeviceData *DeviceDataPtr, SERVO1_TimerUnit_TValueType *TicksPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_ResetCounter (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Resets counter. If counter is counting up then it is set to
**         zero. If counter is counting down then counter is updated to
**         the reload value.
**         The method is not available if HW doesn't allow resetting of
**         the counter.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_ResetCounter(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_GetCounterValue (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the content of counter register. This method can be
**         used both if counter is enabled and if counter is disabled.
**         The method is not available if HW doesn't allow reading of
**         the counter.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Counter value (number of counted ticks).
*/
/* ===================================================================*/
SERVO1_TimerUnit_TValueType SERVO1_TimerUnit_GetCounterValue(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_SetOffsetTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Sets the new offset value to channel specified by the
**         parameter ChannelIdx. It is user responsibility to use value
**         below selected period. This method is available when at
**         least one channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         Ticks           - Number of counter ticks to compare
**                           match.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range.
**                           ERR_NOTAVAIL -  The compare mode is not
**                           selected for selected channel
**                           ERR_PARAM_TICKS - Ticks parameter is out of
**                           possible range.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_SetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, SERVO1_TimerUnit_TValueType Ticks);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_GetOffsetTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the number of counter ticks to compare match channel
**         specified by the parameter ChannelIdx. See also method
**         [SetOffsetTicks]. This method is available when at least one
**         channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         TicksPtr        - Pointer to return value of the
**                           number of counter ticks to compare match.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK 
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range.
**                           ERR_NOTAVAIL -  The compare mode is not
**                           selected for selected channel.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_GetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, SERVO1_TimerUnit_TValueType *TicksPtr);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_SelectOutputAction (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Sets the type of compare match and counter overflow action
**         on channel output. This method is available when at least
**         one channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         CompareAction   - Select output action
**                           on compare match
**     @param
**         CounterAction   - Select output action
**                           on counter overflow
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range
**                           ERR_NOTAVAIL -  Action is not possible on
**                           selected channel or counter. Supported
**                           combinations are HW specific.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError SERVO1_TimerUnit_SelectOutputAction(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, LDD_TimerUnit_TOutAction CompareAction, LDD_TimerUnit_TOutAction CounterAction);

/*
** ===================================================================
**     Method      :  SERVO1_TimerUnit_SetClockConfiguration (component TimerUnit_LDD)
**
**     Description :
**         This method changes the clock configuration. During a clock 
**         configuration change the component changes it's setting 
**         immediately upon a request.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void SERVO1_TimerUnit_SetClockConfiguration(LDD_TDeviceData *DeviceDataPtr, LDD_TClockConfiguration ClockConfiguration);

/* END SERVO1_TimerUnit. */

#ifdef __cplusplus
}  /* extern "C" */
#endif 

#endif
/* ifndef __SERVO1_TimerUnit_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
